apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: linuxtips
spec:
  instanceProfile: "eks-node-instance-profile-dev-myproject"
  amiFamily: "AL2023"
  amiSelectorTerms:
  - id: ami-07a8187677f84efd9
  securityGroupSelectorTerms:
  - id: sg-099b0f5fd8fd47a25
  subnetSelectorTerms:
  - id: subnet-0d9268f489ec2c68b
  - id: subnet-0291e9215d561f7a7
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: linuxtips
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  template:
    metadata:
      labels:
        workload: "etc"  
    spec:
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:   
          - t3
          - t3a

        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
          - medium
          - small

        - key: karpenter.sh/capacity-type
          operator: In
          values:
          - "spot"
          - "on-demand"
    
        - key: "topology.kubernetes.io/zone" 
          operator: In
          values:
          - "us-east-1a"
          - "us-east-1b"
          - "us-east-1c"          
          
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: linuxtips